// Constants
enum CONFIG_HUD
{
    NONE = -1,
    CLUSTER,
    ADVENTURE,
    ADVENTURE_2,
    ADVANCE_2,
    ADVANCE_3,
    EPISODE_II
}

enum CONFIG_STATUS_BAR
{
    OFF,
    ACTIVE,
    ALL
}

enum CONFIG_FLICKER
{
    OFF,
    ORIGINAL,
    VIRTUAL_CONSOLE,
    VIRTUAL_CONSOLE_ADVANCE_3
}

#macro CONFIG_DEFAULT_LIVES true
#macro CONFIG_DEFAULT_TIME_OVER true
#macro CONFIG_DEFAULT_HUD CONFIG_HUD.CLUSTER
#macro CONFIG_DEFAULT_STATUS_BAR CONFIG_STATUS_BAR.ALL
#macro CONFIG_DEFAULT_ITEM_FEED true 
#macro CONFIG_DEFAULT_FLICKER CONFIG_FLICKER.OFF
#macro CONFIG_DEFAULT_DEBUFFS true

// Setup
global.config_database = db_create();
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_LIVES, "lives");
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_TIME_OVER, "time_over");
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_HUD, "hud");
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_STATUS_BAR, "status_bar");
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_ITEM_FEED, "item_feed");
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_FLICKER, "flicker");
db_write(DATABASE_CONFIG, CONFIG_DEFAULT_DEBUFFS, "debuffs");